name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: install and build - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run build

      - name: Install Zip
        uses: montudor/action-zip@v0.1.1

      - name: Zip Dist
        run: |
          ls -a
          echo "lista files"
          cd ~/dist
          echo "Compressing files"
          ls -a
          zip -qq -r -T ../../teste-zip.zip *

      - name: Save Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: teste-zip.zip
          path: teste-zip.zip
          if-no-files-found: error

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      # Baixa o artefato que teve upload no passo de build
      - uses: actions/download-artifact@v2
        with:
          name: teste-zip.zip

      - name: Upload Artifact
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SHH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          overwrite: true
          source: "teste-zip.zip"
          target: "~/artifacts"

      - name: Unzip Artifact
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            unzip -o ~/artifacts/teste-zip.zip -d /var/www/html/api/

      # - name: Deploy teste
      #   uses: appleboy/ssh-action@v0.1.2
      #   with:
      #     host: ${{secrets.SHH_HOST}}
      #     key: ${{secrets.SSH_KEY}}
      #     username: ${{secrets.SSH_USERNAME}}

      #     script: |
      #       mkdir test
      #       mv dist ./test
      #       cd test
      #       mv -v dist/* .
      #       echo "Deu Certo"

      #       https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
